CREATE TABLE fb_weldtype (id VARCHAR not null unique, ktn INTEGER, wty_code VARCHAR, wty_name VARCHAR, PRIMARY KEY (id))
CREATE TABLE fb_weld (id VARCHAR not null unique, ktn Integer, kco INTEGER, wty_code VARCHAR, wld_num VARCHAR, spl_num VARCHAR, iso_num VARCHAR, pdr_size VARCHAR, wld_fw BOOLEAN, wdr_num VARCHAR, wld_wdate DATE, fit_fitting1 VARCHAR, fit_fitting2 VARCHAR, wld_heat1 VARCHAR, wld_heat2 VARCHAR, PRIMARY KEY (id))
CREATE TABLE users(username varchar_ignorecase(50) not null primary key, password varchar_ignorecase(50) not null, enabled boolean not null)
CREATE TABLE authorities(username varchar_ignorecase(50) not null, authority varchar_ignorecase(50) not null, constraint fk_authorities_users foreign key(username) references users(username))
CREATE UNIQUE INDEX ix_auth_username on authorities (username,authority)
INSERT INTO users (username, password, enabled) VALUES ('vinny', '2ac9cb7dc02b3c0083eb70898e549b63', true)
INSERT INTO authorities (username, authority) VALUES ('vinny', 'ROLE_USER')
INSERT INTO users (username, password, enabled) VALUES ('guest', '084e0343a0486ff05530df6c705c8bb4', true)
INSERT INTO authorities (username, authority) VALUES ('guest', 'ROLE_GUEST')